### ISSUE TITLE
Chapter 12 - is 'any' really an adjective? It's used like a determiner

### ISSUE THREAD

**Issue by DJayalath** [Clement25/Speech-and-Language-Processing-ver3-solutions#2]
https://dictionary.cambridge.org/grammar/british-grammar/any

And if used in this way, a new rule should be added for part 9 of question 12.1 as Nominal -> Nominal PP

**Comment by Clement25** [comment]
I see. It can be another choice of rule construction. Here what I refer to is

https://www.merriam-webster.com/dictionary/any
